# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-29 15:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160129_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snake',
            name='image_path',
        ),
    ]
