# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-29 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_snake_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snake',
            name='name',
            field=models.CharField(max_length=140),
        ),
    ]
