# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-29 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20160129_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='snake',
            name='image_path',
            field=models.TextField(default='image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='snake',
            name='latitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='snake',
            name='location',
            field=models.TextField(default=32),
            preserve_default=False,
        ),
    ]
