# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 11:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_kind'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kind',
        ),
    ]
